# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
# >> main >> TOOLS                                                             #
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #

[[main]]
  name = "Tools"
  pageRef = "tools"
  weight = 1

[[main]]
  name = "EnergyFlexEval"
  identifier = "energyflexeval"
  parent = "Tools"
  pageRef = "tools/energyflexeval"
  weight = 2

[[main]]
  name = "Datenmonitor"
  identifier = "datamonitor"
  parent = "Tools"
  pageRef = "tools/datamonitor"
  weight = 3

[[main]]
  name = "Heat Highway"
  identifier = "heat_highway"
  parent = "Tools"
  pageRef = "tools/heat_highway"
  weight = 4

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
# >> main >> WISSEN                                                            #
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #

[[main]]
  name = "Wissen"
  pageRef = "wissen"
  weight = 11

[[main]]
  name = "Strommärkte"
  parent = "Wissen"
  pageRef = "series/strommärkte"
  weight = 12

[[main]]
  name = "Systemdienstleistungen"
  parent = "Wissen"
  pageRef = "series/systemdienstleistungen"
  weight = 13

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
# >> main >> THEMEN                                                            #
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #

[[main]]
  name = "Themen"
  pageRef = "themen"
  weight = 21

[[main]]
  name = "Kapazitätsmechanismen"
  identifier = "themen-kapazitaetsmechanismen"
  parent = "Themen"
  pageRef = "themen/kapazitaetsmechanismen"
  weight = 22

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
# >> main >> LITERATUR                                                         #
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #

[[main]]
  name = "Literatur"
  pageRef = "literature"
  weight = 31

[[main]]
  name = "Kapazitätsmechanismen"
  identifier = "literature-kapazitaetsmechanismen"
  parent = "Literatur"
  pageRef = "literature/kapazitätsmechanismen"
  weight = 32

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
# >> main >> PROJEKTE                                                          #
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #

[[main]]
  name = "Projekte"
  pageRef = "projekte"
  weight = 51

[[main]]
  name = "transpAIrent.energy"
  parent = "Projekte"
  pageRef = "projekte/transpairent-energy"
  weight = 52

[[main]]
  name = "TeKaVe"
  parent = "Projekte"
  pageRef = "projekte/tekave"
  weight = 53

[[main]]
  name = "SETHub"
  parent = "Projekte"
  pageRef = "projekte/SETHub"
  weight = 54

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
# >> main >> GITHUB                                                            #
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #

[[main]]
  pre = "github"
  identifier = "GitHub"
  url = "https://github.com/ait-energy/en.ergie.at"
  weight = 999

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
# >> footer >> GITHUB                                                            #
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #

[[footer]]
  name = "Impressum"
  pageRef = "impressum"
  weight = 10
