# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
# >> main >> ATLAS                                                             #
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #

[[main]]
  name = "Atlas"
  pageRef = "atlas"
  weight = 11

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
# >> main >> WISSEN                                                            #
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #

[[main]]
  name = "Knowledge"
  pageRef = "wissen"
  weight = 11

[[main]]
  name = "Electricity Markets"
  parent = "Knowledge"
  pageRef = "/series/electricity-markets"
  weight = 12

[[main]]
  name = "Ancillary Services"
  parent = "Knowledge"
  pageRef = "/series/ancillary-services"
  weight = 13

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
# >> main >> THEMEN                                                            #
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #

[[main]]
  name = "Topics"
  pageRef = "themen"
  weight = 21

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
# >> main >> TOOLS                                                            #
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #

[[main]]
  name = "Tools"
  pageRef = "tools"
  weight = 41

[[main]]
  name = "EnergyFlexEval"
  identifier = "energyflexeval"
  parent = "Tools"
  pageRef = "tools/energyflexeval"
  weight = 42

[[main]]
  name = "Data Monitor"
  identifier = "datamonitor"
  parent = "Tools"
  pageRef = "tools/datamonitor"
  weight = 43

[[main]]
  name = "Heat Highway"
  identifier = "heat_highway"
  parent = "Tools"
  pageRef = "tools/heat_highway"
  weight = 44

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
# >> main >> PROJEKTE                                                          #
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #

[[main]]
  name = "Projects"
  pageRef = "projekte"
  weight = 41

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
# >> main >> GITHUB                                                            #
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #

[[main]]
  pre = "github"
  identifier = "GitHub"
  url = "https://github.com/ait-energy/en.ergie.at"
  weight = 999

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
# >> footer >> GITHUB                                                            #
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #

[[footer]]
  name = "Imprint"
  pageRef = "impressum"
  weight = 10
